export { SECTION_META } from "./data"
export type { SectionId, SectionMeta } from "./data"
export { WelcomeSection } from "./welcome-section"
export { IdeasSection } from "./ideas-section"
export { GoalsSection } from "./goals-section"
export { JournalSection } from "./journal-section"
export { SketchesSection } from "./sketches-section"
export { NotesSection } from "./notes-section"
export { ContactsSection } from "./contacts-section"
